import {
  Boxes,
  BadgeCheck,
  Braces,
  Cloud,
  Code2,
  Component,
  Building2,
  Camera,
  Database,
  FileCode2,
  Files,
  FileSpreadsheet,
  GitBranch,
  HardDrive,
  Image,
  KeyRound,
  Layers3,
  ListChecks,
  MonitorSmartphone,
  Network,
  Mail,
  MessageSquare,
  Palette,
  PlugZap,
  Puzzle,
  ScrollText,
  Search,
  Server,
  ShieldCheck,
  TableProperties,
  Terminal,
  Timer,
  Trash2,
  Users,
  Wrench,
  Workflow,
} from "lucide-react";
import {
  SiAxios,
  SiBootstrap,
  SiChartdotjs,
  SiCss,
  SiDotnet,
  SiFilezilla,
  SiGithub,
  SiHtml5,
  SiJavascript,
  SiJquery,
  SiJsonwebtokens,
  SiNpm,
  SiNuget,
  SiOpenapiinitiative,
  SiPostman,
  SiReact,
  SiReacthookform,
  SiReactquery,
  SiReactrouter,
  SiReacttable,
  SiRadixui,
  SiShadcnui,
  SiSharp,
  SiSwagger,
  SiTailwindcss,
  SiVite,
  SiZod,
  SiFramer,
  SiEslint,
} from "react-icons/si";

const technologyVisuals = {
  React: [SiReact, "#61DAFB"],
  "React Router": [SiReactrouter, "#CA4245"],
  JavaScript: [SiJavascript, "#F7DF1E"],
  jQuery: [SiJquery, "#0769AD"],
  HTML: [SiHtml5, "#E34F26"],
  CSS: [SiCss, "#663399"],
  "Tailwind CSS": [SiTailwindcss, "#06B6D4"],
  "Shadcn/UI": [SiShadcnui, "#71717A"],
  Bootstrap: [SiBootstrap, "#7952B3"],
  "Chart.js": [SiChartdotjs, "#FF6384"],
  jsPDF: [FileCode2, "#E63946"],
  Vite: [SiVite, "#646CFF"],
  "Responsive Design": [MonitorSmartphone, "#0EA5E9"],
  "Fetch API": [Network, "#2563EB"],
  Axios: [SiAxios, "#5A29E4"],
  SweetAlert2: [BadgeCheck, "#7066E0"],
  Select2: [ListChecks, "#5897FB"],
  SheetJS: [FileSpreadsheet, "#217346"],
  ExcelJS: [FileSpreadsheet, "#107C41"],
  "Face-api.js": [Camera, "#0891B2"],
  "Web Camera API": [Camera, "#7C3AED"],
  "React Query": [SiReactquery, "#FF4154"],
  "TanStack Table": [SiReacttable, "#FF4154"],
  "React Hook Form": [SiReacthookform, "#EC5990"],
  Zod: [SiZod, "#3E67B1"],
  "Framer Motion": [SiFramer, "#BB4BFF"],
  "Radix UI": [SiRadixui, "#71717A"],
  "Context API": [SiReact, "#61DAFB"],
  "Rutas protegidas": [ShieldCheck, "#16A34A"],
  "Protected Routes": [ShieldCheck, "#16A34A"],
  "Validación de formularios": [BadgeCheck, "#16A34A"],
  "Form Validation": [BadgeCheck, "#16A34A"],
  "Temas visuales": [Palette, "#7C3AED"],
  "Visual Themes": [Palette, "#7C3AED"],
  ESLint: [SiEslint, "#4B32C3"],
  ".NET 10": [SiDotnet, "#512BD4"],
  ".NET 8": [SiDotnet, "#512BD4"],
  "ASP.NET Web": [SiDotnet, "#512BD4"],
  "REST APIs": [Network, "#2563EB"],
  "Identity JWT": [SiJsonwebtokens, "#D63AFF"],
  "Authentication & Authorization": [ShieldCheck, "#16A34A"],
  Logging: [ScrollText, "#D97706"],
  "Clean Architecture": [Layers3, "#0891B2"],
  "Fluent Validation": [BadgeCheck, "#16A34A"],
  "Entity Framework Core": [SiDotnet, "#512BD4"],
  "Dependency Injection": [PlugZap, "#D97706"],
  SOLID: [Component, "#0284C7"],
  CORS: [Network, "#EA580C"],
  "Refresh Tokens": [KeyRound, "#D63AFF"],
  "Background Services": [Timer, "#0891B2"],
  "File Handling": [Files, "#D97706"],
  MediatR: [Workflow, "#7C3AED"],
  CQRS: [Workflow, "#2563EB"],
  "Repository Pattern": [Database, "#0F766E"],
  "Custom Middleware": [Layers3, "#D97706"],
  "Soft Delete": [Trash2, "#DC2626"],
  "Options Pattern": [Wrench, "#512BD4"],
  "Roles y permisos": [KeyRound, "#16A34A"],
  "Roles & Permissions": [KeyRound, "#16A34A"],
  "Validación de sesión": [ShieldCheck, "#0891B2"],
  "Session Validation": [ShieldCheck, "#0891B2"],
  "Arquitectura multiempresa": [Building2, "#0F766E"],
  "Multi-tenant Architecture": [Building2, "#0F766E"],
  DDD: [Boxes, "#0F766E"],
  LINQ: [Braces, "#7C3AED"],
  "C#": [SiSharp, "#239120"],
  MVC: [Boxes, "#2563EB"],
  "SQL Server": [Database, "#CC2927"],
  "Modelado de datos": [Boxes, "#0F766E"],
  "Data Modeling": [Boxes, "#0F766E"],
  "T-SQL": [Database, "#CC2927"],
  "Consultas SQL": [Search, "#2563EB"],
  "SQL Queries": [Search, "#2563EB"],
  "Normalización": [TableProperties, "#0F766E"],
  Normalization: [TableProperties, "#0F766E"],
  "Índices": [ListChecks, "#7C3AED"],
  Indexes: [ListChecks, "#7C3AED"],
  Transacciones: [Workflow, "#D97706"],
  Transactions: [Workflow, "#D97706"],
  "Code First": [Code2, "#512BD4"],
  Migraciones: [GitBranch, "#7C3AED"],
  Migrations: [GitBranch, "#7C3AED"],
  "Relaciones y claves foráneas": [Network, "#2563EB"],
  "Relationships & Foreign Keys": [Network, "#2563EB"],
  "Integridad referencial": [ShieldCheck, "#16A34A"],
  "Referential Integrity": [ShieldCheck, "#16A34A"],
  "Seed de datos": [Database, "#D97706"],
  "Data Seeding": [Database, "#D97706"],
  "Optimización de consultas": [Search, "#EA580C"],
  "Query Optimization": [Search, "#EA580C"],
  Swagger: [SiSwagger, "#85EA2D"],
  OpenAPI: [SiOpenapiinitiative, "#6BA539"],
  "Visual Studio": [Code2, "#A855F7"],
  "VS Code": [Code2, "#007ACC"],
  npm: [SiNpm, "#CB3837"],
  NuGet: [SiNuget, "#004880"],
  ".NET CLI": [Terminal, "#512BD4"],
  "EF Core Tools": [Wrench, "#512BD4"],
  "IIS Server": [Server, "#0078D4"],
  "ASP.NET Core Module": [SiDotnet, "#512BD4"],
  "dotnet publish": [Terminal, "#512BD4"],
  "Web.config": [FileCode2, "#D97706"],
  "Hosting In-Process": [Server, "#0891B2"],
  "Configuración por ambientes": [Wrench, "#0F766E"],
  "Environment Configuration": [Wrench, "#0F766E"],
  "Git / GitHub": [SiGithub, "#64748B"],
  Postman: [SiPostman, "#FF6C37"],
  "Monster ASP.NET": [SiDotnet, "#512BD4"],
  DonWeb: [Cloud, "#2563EB"],
  "SSL/TLS": [ShieldCheck, "#16A34A"],
  FileZilla: [SiFilezilla, "#BF0000"],
  "Arquitectura de software": [Layers3, "#7C3AED"],
  "Software Architecture": [Layers3, "#7C3AED"],
  "Patrones de diseño": [Workflow, "#D97706"],
  "Design Patterns": [Workflow, "#D97706"],
  Refactoring: [Component, "#0284C7"],
  "Resolución de problemas": [Search, "#EA580C"],
  "Problem Solving": [Search, "#EA580C"],
  "Trabajo en equipo": [Users, "#2563EB"],
  Teamwork: [Users, "#2563EB"],
  "Programación orientada a objetos": [Component, "#0284C7"],
  "Object-Oriented Programming": [Component, "#0284C7"],
  "Arquitectura por capas": [Layers3, "#7C3AED"],
  "Layered Architecture": [Layers3, "#7C3AED"],
  "Patrón DTO": [Puzzle, "#D97706"],
  "DTO Pattern": [Puzzle, "#D97706"],
  "Manejo de excepciones": [ShieldCheck, "#DC2626"],
  "Exception Handling": [ShieldCheck, "#DC2626"],
  "Modelado relacional": [TableProperties, "#0F766E"],
  "Relational Modeling": [TableProperties, "#0F766E"],
  "Code Review": [BadgeCheck, "#16A34A"],
  "Amazon S3": [Cloud, "#FF9900"],
  "Almacenamiento local": [HardDrive, "#64748B"],
  "Local File Storage": [HardDrive, "#64748B"],
  ImageMagick: [Image, "#0891B2"],
  MailKit: [Mail, "#EA4335"],
  Twilio: [MessageSquare, "#F22F46"],
};

const TechnologyBadge = ({ name, compact = false }) => {
  const [Icon, color] = technologyVisuals[name] ?? [Code2, "#2563EB"];

  return (
    <span
      className={`inline-flex items-center font-bold text-slate-600 dark:text-slate-300 ${
        compact
          ? "gap-1.5 rounded px-2 py-1 text-[11px]"
          : "gap-2 rounded-md px-2.5 py-1.5 text-xs"
      } bg-slate-100 dark:bg-white/5`}
    >
      <Icon size={compact ? 12 : 14} style={{ color }} className="shrink-0" aria-hidden="true" />
      <span>{name}</span>
    </span>
  );
};

export default TechnologyBadge;
